In [11]:
import pandas as pd
import requests
import json

In [12]:
import http.client

conn = http.client.HTTPSConnection("api.ambeedata.com")

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
    }

conn.request("GET", "/disasters/latest/by-continent?continent=NAR&limit=50&page=1", headers=headers)

In [13]:
res = conn.getresponse()
data = res.read()
data = data.decode("utf-8")
json_data = json.loads(data)

In [14]:
json_data

{'message': 'success',
 'hasNextPage': True,
 'page': 1,
 'limit': 50,
 'result': [{'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-27 12:00:00',
   'lat': 62.0814,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -147.4873,
   'source_event_id': '11888884',
   'event_id': '66e21b56bb7a6d67265ec424'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-27 11:00:00',
   'lat': 63.8772,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -145.6294,
   'source_event_id': '11888869',
   'event_id': '66de5ed2bb7a6d672608d34e'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-27 10:00:00',
   'lat': 46.688,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -111.459833,
   'source_event_id': '11888908',
   'event_id': '66c703c472c3d1a4e410be6a'},
  {'event_type': 'DR',
   'event_name': 'Drought in Canada',
   'date': '2024-09-27 09:00:00',
   'lat': 53.5,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-27 14:50:54',
   'lng': -116,
   'source_event_id': '1017111',
   'event_id': '66c703f672c3d1a4e413d420'},
  {'event_type': 'TC',
   'event_name': 'Tropical Cyclone JOHN-24',
   'date': '2024-09-27 09:00:00',
   'lat': 20.3,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-27 14:50:54',
   'lng': -107.6,
   'source_event_id': '1001100',
   'event_id': '66e36cc7bb7a6d67267d34cc'},
  {'event_type': 'DR',
   'event_name': 'Drought in United States',
   'date': '2024-09-27 09:00:00',
   'lat': 39.5,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -78.5,
   'source_event_id': '1017227',
   'event_id': '66ea0457bb7a6d6726178731'},
  {'event_type': 'TC',
   'event_name': 'Tropical Cyclone HELENE-24',
   'date': '2024-09-27 09:00:00',
   'lat': 25.5,
   'continent': 'nar',
   'country_code': 'CUB',
   'created_time': '2024-09-27 14:50:54',
   'lng': -85.5,
   'source_event_id': '1001101',
   'event_id': '66f34276bb7a6d6726f06c4a'},
  {'event_type': 'DR',
   'event_name': 'Drought in Mexico, United States',
   'date': '2024-09-27 09:00:00',
   'lat': 16.794,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-27 14:50:54',
   'lng': -98,
   'source_event_id': '1016963',
   'event_id': '66f4237fbb7a6d672604fac1'},
  {'event_type': 'TC',
   'event_name': 'Tropical Cyclone ISAAC-24',
   'date': '2024-09-27 09:00:00',
   'lat': 37.10073601511491,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-27 14:50:54',
   'lng': -54.1,
   'source_event_id': '1001103',
   'event_id': '66f521b7bb7a6d67261cb9c3'},
  {'event_type': 'SW',
   'event_name': 'Hurricane Isaac',
   'date': '2024-09-27 09:00:00',
   'lat': 37.04900857016478,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-27 14:50:54',
   'lng': -48.5,
   'source_event_id': 'EONET_11324',
   'event_id': '66f6c650bb7a6d6726435e65'},
  {'event_type': 'SW',
   'event_name': 'Hurricane Helene',
   'date': '2024-09-27 09:00:00',
   'lat': 32.84900857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -83,
   'source_event_id': 'EONET_11304',
   'event_id': '66f6c650bb7a6d6726435eb3'},
  {'event_type': 'EQ',
   'event_name': 'M 2.8 - 68 km NE of Arctic Village, Alaska',
   'date': '2024-09-27 08:00:00',
   'lat': 68.57300857016477,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -144.2783,
   'source_event_id': 'ak024cgbr163',
   'event_id': '66f6c650bb7a6d672643611f'},
  {'event_type': 'EQ',
   'event_name': 'SOUTHERN ALASKA',
   'date': '2024-09-27 07:00:00',
   'lat': 61.6254,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -146.0974,
   'source_event_id': '11888823',
   'event_id': '66c7041b72c3d1a4e4161759'},
  {'event_type': 'SW',
   'event_name': 'Hurricane John',
   'date': '2024-09-27 06:00:00',
   'lat': 17.64900857016478,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-27 14:50:54',
   'lng': -103,
   'source_event_id': 'EONET_11265',
   'event_id': '66f5e564bb7a6d67262df1b2'},
  {'event_type': 'EQ',
   'event_name': 'EASTERN GREENLAND',
   'date': '2024-09-27 06:00:00',
   'lat': 78.7232,
   'continent': 'nar',
   'country_code': 'GRL',
   'created_time': '2024-09-27 14:50:54',
   'lng': -19.7205,
   'source_event_id': '11888822',
   'event_id': '66f671fcbb7a6d67263b6d89'},
  {'event_type': 'EQ',
   'event_name': 'M 4.4 - eastern Greenland',
   'date': '2024-09-27 06:00:00',
   'lat': 78.77220857016479,
   'continent': 'nar',
   'country_code': 'GRL',
   'created_time': '2024-09-27 14:50:54',
   'lng': -19.7205,
   'source_event_id': 'us7000ngri',
   'event_id': '66f671fdbb7a6d67263b7859'},
  {'event_type': 'EQ',
   'event_name': 'ARKANSAS',
   'date': '2024-09-27 00:00:00',
   'lat': 35.1015,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -91.480167,
   'source_event_id': '11888887',
   'event_id': '66f6c651bb7a6d6726436412'},
  {'event_type': 'EQ',
   'event_name': 'ALASKA PENINSULA',
   'date': '2024-09-26 22:00:00',
   'lat': 56.3375,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -159.354167,
   'source_event_id': '11888774',
   'event_id': '66c703da72c3d1a4e41202fa'},
  {'event_type': 'EQ',
   'event_name': 'UTAH',
   'date': '2024-09-26 22:00:00',
   'lat': 40.474,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -111.48,
   'source_event_id': '11888735',
   'event_id': '66c7042472c3d1a4e416a7aa'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-26 22:00:00',
   'lat': 45.301167,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -110.902,
   'source_event_id': '11888913',
   'event_id': '66f6c651bb7a6d6726436298'},
  {'event_type': 'EQ',
   'event_name': 'UTAH',
   'date': '2024-09-26 18:00:00',
   'lat': 37.877,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -112.475,
   'source_event_id': '11888686',
   'event_id': '66f5e565bb7a6d67262df414'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-26 17:00:00',
   'lat': 48.772,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -112.267167,
   'source_event_id': '11888726',
   'event_id': '66f5e565bb7a6d67262df436'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL TEXAS',
   'date': '2024-09-26 16:00:00',
   'lat': 29.839,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -98.17,
   'source_event_id': '11888651',
   'event_id': '66f34277bb7a6d6726f072c2'},
  {'event_type': 'EQ',
   'event_name': 'OKLAHOMA',
   'date': '2024-09-26 16:00:00',
   'lat': 34.738667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -98.448333,
   'source_event_id': '11888652',
   'event_id': '66f5e565bb7a6d67262df447'},
  {'event_type': 'EQ',
   'event_name': 'M 4.0 - 12 km E of Saanichton, Canada',
   'date': '2024-09-26 11:00:00',
   'lat': 48.629675236831446,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -123.24783333333333,
   'source_event_id': 'uw62050041',
   'event_id': '66c946f74e6e6f71509cfc9c'},
  {'event_type': 'WF',
   'event_name': 'LONG HOLLOW Wildfire, Whitman, Washington',
   'date': '2024-09-26 10:00:00',
   'lat': 46.73940857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -117.573,
   'source_event_id': 'EONET_11326',
   'event_id': '66f5e564bb7a6d67262df0d6'},
  {'event_type': 'EQ',
   'event_name': 'YELLOWSTONE REGION, WYOMING',
   'date': '2024-09-26 07:00:00',
   'lat': 44.45,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -110.9385,
   'source_event_id': '11888587',
   'event_id': '66c703c572c3d1a4e410cf6d'},
  {'event_type': 'EQ',
   'event_name': 'M 2.9 - 2 km N of Álvaro Obregón, Mexico',
   'date': '2024-09-26 06:00:00',
   'lat': 19.42710857016478,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-27 14:50:54',
   'lng': -99.2037,
   'source_event_id': 'us7000nghz',
   'event_id': '66f521b8bb7a6d67261cbc50'},
  {'event_type': 'EQ',
   'event_name': 'WASHINGTON',
   'date': '2024-09-26 04:00:00',
   'lat': 47.537833,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -121.812833,
   'source_event_id': '11888650',
   'event_id': '66e21b56bb7a6d67265ec42d'},
  {'event_type': 'EQ',
   'event_name': 'SOUTHERN ILLINOIS',
   'date': '2024-09-26 02:00:00',
   'lat': 38.772833,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -89.3675,
   'source_event_id': '11888456',
   'event_id': '66f521b8bb7a6d67261cbd5c'},
  {'event_type': 'EQ',
   'event_name': 'NEVADA',
   'date': '2024-09-26 00:00:00',
   'lat': 39.4928,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -119.5076,
   'source_event_id': '11888418',
   'event_id': '66c703d972c3d1a4e4120094'},
  {'event_type': 'EQ',
   'event_name': 'MISSOURI-ARKANSAS BORDER REGION',
   'date': '2024-09-26 00:00:00',
   'lat': 36.034167,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -91.700167,
   'source_event_id': '11888602',
   'event_id': '66c7040272c3d1a4e41490d1'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-25 23:00:00',
   'lat': 64.9856,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -147.4266,
   'source_event_id': '11888405',
   'event_id': '66c703c472c3d1a4e410be41'},
  {'event_type': 'EQ',
   'event_name': 'M 3.2 - 14 km S of Eunice, New Mexico',
   'date': '2024-09-25 23:00:00',
   'lat': 32.35540857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -103.1818,
   'source_event_id': 'us7000nggh',
   'event_id': '66e8eadfbb7a6d6726fed272'},
  {'event_type': 'EQ',
   'event_name': 'CALIFORNIA-NEVADA BORDER REGION',
   'date': '2024-09-25 20:00:00',
   'lat': 36.5271,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -115.0989,
   'source_event_id': '11888350',
   'event_id': '66c703c372c3d1a4e410aa62'},
  {'event_type': 'EQ',
   'event_name': 'NEVADA',
   'date': '2024-09-25 19:00:00',
   'lat': 38.5876,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -116.4255,
   'source_event_id': '11888332',
   'event_id': '66c7040c72c3d1a4e4152750'},
  {'event_type': 'EQ',
   'event_name': 'WASHINGTON-OREGON BORDER REGION',
   'date': '2024-09-25 18:00:00',
   'lat': 45.376333,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -121.7195,
   'source_event_id': '11888482',
   'event_id': '66c703f272c3d1a4e41393bf'},
  {'event_type': 'WF',
   'event_name': 'GOOSMUS Wildfire, Ferry, Washington',
   'date': '2024-09-25 18:00:00',
   'lat': 48.99584157016478,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-27 14:50:54',
   'lng': -118.554467,
   'source_event_id': 'EONET_11327',
   'event_id': '66f5e564bb7a6d67262df0fa'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-25 15:00:00',
   'lat': 62.0755,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -145.0283,
   'source_event_id': '11888268',
   'event_id': '66c703c372c3d1a4e410a8a2'},
  {'event_type': 'WF',
   'event_name': 'KELLY LANE Wildfire, Yakima, Washington',
   'date': '2024-09-25 14:00:00',
   'lat': 46.68670857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -120.3753,
   'source_event_id': 'EONET_11329',
   'event_id': '66f5e564bb7a6d67262df103'},
  {'event_type': 'EQ',
   'event_name': 'NEVADA',
   'date': '2024-09-25 10:00:00',
   'lat': 38.2077,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -117.7542,
   'source_event_id': '11888213',
   'event_id': '66ee30efbb7a6d67267bc883'},
  {'event_type': 'EQ',
   'event_name': 'HEBGEN LAKE REGION',
   'date': '2024-09-25 09:00:00',
   'lat': 44.776,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -111.2255,
   'source_event_id': '11888244',
   'event_id': '66eb8e68bb7a6d67263c5f49'},
  {'event_type': 'EQ',
   'event_name': 'M 3.3 - 102 km SE of Leilani Estates, Hawaii',
   'date': '2024-09-25 08:00:00',
   'lat': 18.88950857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -154.2073,
   'source_event_id': 'us7000ng41',
   'event_id': '66f493dcbb7a6d67260ef880'},
  {'event_type': 'EQ',
   'event_name': 'OKLAHOMA',
   'date': '2024-09-25 07:00:00',
   'lat': 35.8615,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -96.7815,
   'source_event_id': '11888227',
   'event_id': '66c703c372c3d1a4e410a89f'},
  {'event_type': 'EQ',
   'event_name': 'NORTHERN CALIFORNIA',
   'date': '2024-09-25 07:00:00',
   'lat': 39.7901,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -120.6559,
   'source_event_id': '11888416',
   'event_id': '66ea3c84bb7a6d67261d3046'},
  {'event_type': 'EQ',
   'event_name': 'NORTHERN ALASKA',
   'date': '2024-09-25 07:00:00',
   'lat': 66.7525,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -146.8658,
   'source_event_id': '11888186',
   'event_id': '66ed882cbb7a6d67266c09b2'},
  {'event_type': 'EQ',
   'event_name': 'M 2.7 - 8 km NE of Cedar Point, Kansas',
   'date': '2024-09-25 07:00:00',
   'lat': 38.37220857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -96.7606,
   'source_event_id': 'us7000ng3p',
   'event_id': '66f3cdc1bb7a6d6726fd03e1'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-25 04:00:00',
   'lat': 45.154667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -112.612333,
   'source_event_id': '11888270',
   'event_id': '66d7c7a2bb7a6d672672d690'},
  {'event_type': 'EQ',
   'event_name': 'NEVADA',
   'date': '2024-09-25 03:00:00',
   'lat': 39.3983,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -117.6915,
   'source_event_id': '11888414',
   'event_id': '66f4cd53bb7a6d672614d8f9'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-25 02:00:00',
   'lat': 45.0265,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-27 14:50:54',
   'lng': -111.927333,
   'source_event_id': '11888263',
   'event_id': '66f4cd53bb7a6d672614d91f'}]}

In [31]:
data = pd.DataFrame(json_data['result'])[['event_type','event_name','date','lat','lng','continent','country_code','created_time']]
data

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,TC,Tropical Cyclone ISAAC-24,2024-09-27 09:00:00,38.800736,-42.400000,ocean,PRT,2024-09-27 14:51:22
1,EQ,Earthquake in,2024-09-26 19:00:00,-17.187500,66.069791,ocean,MUS,2024-09-27 14:51:22
2,EQ,M 5.4 - Mauritius - Reunion region,2024-09-22 20:00:00,-17.315291,66.498300,ocean,MUS,2024-09-27 14:51:22
3,EQ,M 5.1 - South Indian Ocean,2024-09-19 10:00:00,-5.554591,82.621800,ocean,IOT,2024-09-27 14:51:22
4,EQ,M 4.9 - southern Mid-Atlantic Ridge,2024-09-17 17:00:00,-24.510391,-13.600500,ocean,SHN,2024-09-27 14:51:22
5,TC,Tropical Cyclone GORDON-24,2024-09-17 09:00:00,27.600000,-44.600000,ocean,PRT,2024-09-17 14:35:21
6,EQ,Earthquake in,2024-09-10 23:00:00,-55.804167,-25.196055,ocean,SGS,2024-09-11 22:36:03
7,EQ,M 5.0 - Mid-Indian Ridge,2024-09-09 06:00:00,-22.451091,69.220800,ocean,MUS,2024-09-27 14:51:22
8,EQ,MID-INDIAN RIDGE,2024-09-09 06:00:00,-22.500100,69.220800,ocean,MUS,2024-09-11 22:36:03
9,EQ,M 4.5 - northern Mid-Atlantic Ridge,2024-09-01 17:00:00,31.209709,-40.883100,ocean,PRT,2024-09-27 14:51:22
10,EQ,M 4.8 - northern Mid-Atlantic Ridge,2024-09-01 15:00:00,26.432809,-44.579300,ocean,PRT,2024-09-27 14:51:22
11,EQ,M 4.6 - Mid-Indian Ridge,2024-09-01 01:00:00,-10.397891,66.382500,ocean,IOT,2024-09-27 14:51:22
12,EQ,M 4.6 - southern Mid-Atlantic Ridge,2024-08-29 17:00:00,-41.592891,-16.414300,ocean,SGS,2024-09-27 14:51:22

In [17]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 10):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=NAR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,CENTRAL ALASKA,2024-09-27 12:00:00,62.081400,-147.487300,nar,USA,2024-09-27 14:50:54
1,EQ,CENTRAL ALASKA,2024-09-27 11:00:00,63.877200,-145.629400,nar,USA,2024-09-27 14:50:54
2,EQ,MONTANA,2024-09-27 10:00:00,46.688000,-111.459833,nar,USA,2024-09-27 14:50:54
3,DR,Drought in Canada,2024-09-27 09:00:00,53.500000,-116.000000,nar,CAN,2024-09-27 14:50:54
4,TC,Tropical Cyclone JOHN-24,2024-09-27 09:00:00,20.300000,-107.600000,nar,MEX,2024-09-27 14:50:54
...,...,...,...,...,...,...,...,...
404,SW,Hurricane Gilma,2024-08-29 18:00:00,20.149009,-151.100000,nar,USA,2024-09-04 02:36:10
405,WF,"DeSoto BB 7208 RX Wildfire, Perry, Mississippi",2024-08-29 16:00:00,31.105509,-88.928000,nar,USA,2024-09-27 14:50:54
406,TC,Tropical Cyclone HECTOR-24,2024-08-29 09:00:00,16.500000,-125.800000,nar,MEX,2024-08-30 02:35:27
407,EQ,"M 2.5 - 5 km SE of Hill City, Kansas",2024-08-29 00:00:00,39.373409,-99.799700,nar,USA,2024-09-27 14:50:54
408,EQ,SOUTHERN ALASKA,2024-08-28 19:00:00,60.210600,-143.522800,nar,USA,2024-08-30 14:37:03

In [18]:
df['country_code'].unique()

array(['USA', 'CAN', 'MEX', 'CUB', 'GRL', 'FRA', 'BRB', 'DOM', 'GTM',
       'VGB', 'TTO', 'PAN', 'ATG'], dtype=object)

In [21]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 15):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ASIA&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df1 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df1

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,SW,Light Rain at Agartala,2024-09-27 14:00:00,24.092599,92.238955,asia,IND,2024-09-27 14:51:08
1,SW,Thunderstorm with Lightning at Bengaluru,2024-09-27 14:00:00,12.943592,77.553069,asia,IND,2024-09-27 14:51:08
2,SW,Light Rain at Mumbai,2024-09-27 13:00:00,19.156937,74.855242,asia,IND,2024-09-27 14:51:08
3,SW,Thunder shower with strong wind at Thiruvanant...,2024-09-27 13:00:00,9.503190,76.410583,asia,IND,2024-09-27 14:51:08
4,SW,Light Thunderstorms at Ranchi,2024-09-27 13:00:00,23.159896,84.464228,asia,IND,2024-09-27 14:51:08
...,...,...,...,...,...,...,...,...
594,SW,Moderate Thunderstorms at Chennai,2024-08-29 13:00:00,11.153182,79.264944,asia,IND,2024-08-29 14:36:11
595,EQ,"M 4.4 - 176 km SE of Pondaguitan, Philippines",2024-08-29 13:00:00,5.096709,127.083900,asia,IDN,2024-09-27 14:51:08
596,SW,Lightning at SDMA,2024-08-29 09:00:00,13.967177,77.093196,asia,IND,2024-08-30 02:35:08
597,EQ,Earthquake in Afghanistan,2024-08-29 05:00:00,34.971916,69.274778,asia,AFG,2024-08-30 02:35:08
598,WF,Forest fires in Russian Federation,2024-08-29 00:00:00,45.715435,37.970809,asia,RUS,2024-08-30 02:35:08

In [19]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=SAR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df2 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df2

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,DR,"Drought in Bolivia, Brazil, Colombia, Ecuador,...",2024-09-27 09:00:00,-15.500000,-61.000000,sar,BOL,2024-09-27 14:51:08
1,EQ,"M 2.9 - 49 km S of San Lorenzo de Esmeraldas, ...",2024-09-27 00:00:00,0.889709,-78.780600,sar,ECU,2024-09-27 14:51:08
2,EQ,M 5.1 - West Chile Rise,2024-09-26 22:00:00,-41.430191,-86.335800,sar,CHL,2024-09-27 14:51:08
3,EQ,M 4.8 - southern East Pacific Rise,2024-09-24 06:00:00,-25.404691,-115.954000,sar,CHL,2024-09-27 14:51:08
4,EQ,"M 5.0 - 51 km W of Salsacate, Argentina",2024-09-24 00:00:00,-31.313991,-65.628600,sar,ARG,2024-09-27 14:51:08
...,...,...,...,...,...,...,...,...
149,WF,Wildfire in Brazil 1021892,2024-08-28 19:00:00,-12.733510,-58.348210,sar,BRA,2024-09-27 14:51:08
150,WF,Wildfire in Brazil 1021908,2024-08-28 19:00:00,-10.267216,-49.741072,sar,BRA,2024-09-27 14:51:08
151,WF,Wildfire in Brazil 1021892,2024-08-28 19:00:00,-12.733510,-58.348210,sar,BRA,2024-09-27 14:51:08
152,WF,Wildfire in Brazil 1021900,2024-08-28 19:00:00,-14.843561,-55.688173,sar,BRA,2024-09-27 14:51:08
153,WF,Wildfire in Brazil 1021934,2024-08-28 19:00:00,-9.643191,-53.654064,sar,BRA,2024-09-27 14:51:08

In [20]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 2):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ANT&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df4 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df4

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,M 5.3 - southern Mid-Atlantic Ridge,2024-09-25 14:00:00,-57.682991,-6.905300,ant,ATA,2024-09-27 14:51:21
1,EQ,Earthquake in,2024-09-25 14:00:00,-57.729072,-7.032034,ant,ATA,2024-09-26 22:51:42
2,EQ,M 4.5 - Bouvet Island region,2024-09-09 20:00:00,-53.922491,6.907000,ant,ATA,2024-09-27 14:51:21
3,EQ,M 5.0 - Pacific-Antarctic Ridge,2024-09-06 18:00:00,-58.236091,-139.944100,ant,ATA,2024-09-27 14:51:21
4,EQ,M 4.8 - Balleny Islands region,2024-08-31 19:00:00,-64.381191,174.802700,ant,ATA,2024-09-27 14:51:21
5,EQ,M 4.5 - South Shetland Islands,2024-08-31 13:00:00,-60.934391,-53.829100,ant,ATA,2024-09-27 14:51:21
6,EQ,M 4.5 - Drake Passage,2024-08-30 16:00:00,-59.175491,-60.942900,ant,ATA,2024-09-27 14:51:21

In [22]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 15):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ASIA&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df3 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df3

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,SW,Light Rain at Agartala,2024-09-27 14:00:00,24.092599,92.238955,asia,IND,2024-09-27 14:51:08
1,SW,Thunderstorm with Lightning at Bengaluru,2024-09-27 14:00:00,12.943592,77.553069,asia,IND,2024-09-27 14:51:08
2,SW,Light Rain at Mumbai,2024-09-27 13:00:00,19.156937,74.855242,asia,IND,2024-09-27 14:51:08
3,SW,Thunder shower with strong wind at Thiruvanant...,2024-09-27 13:00:00,9.503190,76.410583,asia,IND,2024-09-27 14:51:08
4,SW,Light Thunderstorms at Ranchi,2024-09-27 13:00:00,23.159896,84.464228,asia,IND,2024-09-27 14:51:08
...,...,...,...,...,...,...,...,...
594,SW,Moderate Thunderstorms at Chennai,2024-08-29 13:00:00,11.153182,79.264944,asia,IND,2024-08-29 14:36:11
595,EQ,"M 4.4 - 176 km SE of Pondaguitan, Philippines",2024-08-29 13:00:00,5.096709,127.083900,asia,IDN,2024-09-27 14:51:08
596,SW,Lightning at SDMA,2024-08-29 09:00:00,13.967177,77.093196,asia,IND,2024-08-30 02:35:08
597,EQ,Earthquake in Afghanistan,2024-08-29 05:00:00,34.971916,69.274778,asia,AFG,2024-08-30 02:35:08
598,WF,Forest fires in Russian Federation,2024-08-29 00:00:00,45.715435,37.970809,asia,RUS,2024-08-30 02:35:08

In [23]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 5):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=AFR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df5 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df5

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,DR,"Drought in Botswana, Namibia, South Africa",2024-09-27 09:00:00,-25.505500,19.000000,afr,NAM,2024-09-27 14:51:22
1,DR,"Drought in Algeria, Spain, Morocco, Tunisia",2024-09-27 09:00:00,34.230500,-1.500000,afr,DZA,2024-09-27 14:51:22
2,DR,"Drought in Burkina Faso, Cote d'Ivoire, Ghana,...",2024-09-27 09:00:00,7.500000,-4.000000,afr,CIV,2024-09-27 14:51:22
3,DR,"Drought in Cameroon, Nigeria",2024-09-27 09:00:00,8.500000,7.500000,afr,NGA,2024-09-27 14:51:22
4,DR,"Drought in Angola, Burundi, Democratic Republi...",2024-09-27 09:00:00,-1.500000,17.000000,afr,COD,2024-09-27 14:51:22
...,...,...,...,...,...,...,...,...
127,WF,Wildfire in South Africa 1021858,2024-08-28 19:00:00,-30.975426,28.127271,afr,ZAF,2024-09-27 14:51:22
128,WF,Wildfire in Zambia 1021949,2024-08-28 19:00:00,-9.857168,31.667448,afr,ZMB,2024-09-27 14:51:22
129,WF,Wildfire in South Africa 1021859,2024-08-28 19:00:00,-31.075402,28.042633,afr,ZAF,2024-09-27 14:51:22
130,WF,Wildfire in Zambia 1021860,2024-08-28 19:00:00,-10.735421,29.250183,afr,ZMB,2024-09-27 14:51:22
131,WF,Wildfire in Angola 1021904,2024-08-28 19:00:00,-16.695203,17.192252,afr,AGO,2024-09-27 14:51:22

In [24]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 5):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=EUR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df6 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df6

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,DR,"Drought in Bosnia and Herzegovina, Bulgaria,...",2024-09-27 09:00:00,45.521500,24.000000,eur,ROU,2024-09-27 14:51:32
1,DR,"Drought in Kazakhstan, Moldova, Romania, Russi...",2024-09-27 09:00:00,47.980000,34.500000,eur,UKR,2024-09-27 14:51:32
2,EQ,"M 4.0 - 89 km WSW of Palaióchora, Greece",2024-09-27 02:00:00,35.057509,22.736900,eur,GRC,2024-09-27 14:51:32
3,FL,"Flood in Albania, Montenegro",2024-09-26 01:00:00,42.250768,19.595972,eur,ALB,2024-09-27 14:51:32
4,FL,Flood in Croatia,2024-09-25 12:00:00,45.673449,18.957527,eur,SRB,2024-09-27 14:51:32
5,FL,Flood in Italy,2024-09-25 01:00:00,40.814800,14.629494,eur,ITA,2024-09-26 22:51:13
6,EQ,M 5.0 - Greenland Sea,2024-09-23 05:00:00,73.268209,6.416400,eur,NOR,2024-09-27 14:51:32
7,FL,Flood in United Kingdom,2024-09-23 01:00:00,52.847891,-2.165016,eur,GBR,2024-09-24 22:51:24
8,FL,Flood in Germany,2024-09-22 12:00:00,52.075383,14.735794,eur,DEU,2024-09-27 14:51:32
9,EQ,"M 4.5 - 10 km SSW of Pribinić, Bosnia and Herz...",2024-09-22 12:00:00,44.574309,17.647600,eur,BIH,2024-09-27 14:51:32
10,EQ,"M 3.8 - 13 km WNW of Favignana, Italy",2024-09-21 03:00:00,38.032109,12.197800,eur,ITA,2024-09-27 14:51:32
11,FL,Flood in Greece,2024-09-20 01:00:00,37.756180,23.666901,eur,GRC,2024-09-21 22:33:54
12,FL,Flood in Spain,2024-09-20 01:00:00,40.445926,0.409663,eur,ESP,2024-09-21 22:33:54
13,FL,Flood in Italy,2024-09-19 08:00:00,46.114378,13.046942,eur,ITA,2024-09-20 22:34:54
14,WF,Forest fires in Portugal,2024-09-19 00:00:00,41.103663,-8.488323,eur,PRT,2024-09-20 22:34:54
15,FL,"Flood in Dresden, Germany",2024-09-18 12:00:00,51.051891,13.729820,eur,DEU,2024-09-27 14:51:32
16,FL,"Flood in Austria, Czech Republic, Germany, Pol...",2024-09-18 09:00:00,49.859190,17.672090,eur,CZE,2024-09-19 08:35:46
17,FL,"Flood in Emilia-Romagna, Italy",2024-09-18 06:00:00,44.281576,11.891452,eur,ITA,2024-09-27 14:51:32
18,WF,Wildfire in Portugal,2024-09-15 11:00:00,40.684092,-8.508224,eur,PRT,2024-09-27 14:51:32
19,WF,Wildfire in Portugal 1022227,2024-09-14 19:00:00,40.749652,-8.416358,eur,PRT,2024-09-27 14:51:32
20,WF,"Wildfire in Ukraine, Russian Federation 1022230",2024-09-14 19:00:00,48.724663,39.624686,eur,UKR,2024-09-27 14:51:32
21,EQ,"M 4.3 - 68 km SE of Ramatuelle, France",2024-09-14 18:00:00,42.848809,7.228200,eur,FRA,2024-09-27 14:51:32
22,FL,"Flood in Lower Austria, Austria",2024-09-14 12:00:00,48.185061,16.376631,eur,AUT,2024-09-27 14:51:32
23,FL,"Flood in Brandenbourg, Germany",2024-09-14 12:00:00,51.948906,14.700623,eur,POL,2024-09-27 14:51:32
24,FL,"Flood in Galati and Vaslui counties, Romania",2024-09-14 05:00:00,45.788551,27.668568,eur,ROU,2024-09-27 14:51:32
25,FL,Flood in Slovenia,2024-09-14 01:00:00,46.149028,14.626289,eur,SVN,2024-09-15 22:36:27
26,FL,Flood in South West Poland,2024-09-14 00:00:00,50.603763,16.667259,eur,POL,2024-09-27 14:51:32
27,WF,Wildfire in Portugal 1022235,2024-09-13 19:00:00,41.599329,-7.897557,eur,PRT,2024-09-27 14:51:32
28,FL,"Flood in March, Morava Basins, Slovakia",2024-09-13 15:00:00,48.394821,16.913951,eur,SVK,2024-09-27 14:51:32
29,FL,"Flood on the Danube in Hungary, Austria, and S...",2024-09-13 06:00:00,47.750803,17.974132,eur,HUN,2024-09-27 14:51:32
30,FL,"Flood in Bulgaria, Romania",2024-09-13 01:00:00,43.182253,27.686768,eur,BGR,2024-09-14 14:34:58
31,EQ,"M 4.6 - 24 km NNE of Levídion, Greece",2024-09-11 04:00:00,37.943109,22.353500,eur,GRC,2024-09-27 14:51:32
32,FL,Flood in Croatia,2024-09-11 01:00:00,42.692431,17.270607,eur,HRV,2024-09-12 14:36:37
33,FL,Flood in Norway,2024-09-11 01:00:00,60.985066,10.844528,eur,NOR,2024-09-12 14:36:37
34,FL,Flood in France,2024-09-09 01:00:00,45.341614,6.858755,eur,FRA,2024-09-10 22:36:40
35,FL,Flood in Spain,2024-09-09 01:00:00,42.281464,-2.482805,eur,ESP,2024-09-10 22:36:40
36,FL,Flood in United Kingdom,2024-09-09 01:00:00,51.557031,-3.564207,eur,GBR,2024-09-10 22:36:40
37,WF,"Wildfires in Saxony-Anhalt, Germany",2024-09-06 00:00:00,51.778454,12.404770,eur,DEU,2024-09-27 14:51:32
38,FL,Rivers in Europe Burst Their Banks,2024-09-04 00:00:00,50.818231,17.645847,eur,POL,2024-09-27 14:51:32
39,EQ,"M 5.1 - 107 km WNW of Höfn, Iceland",2024-09-03 16:00:00,64.612209,-17.322400,eur,ISL,2024-09-27 14:51:32
40,EQ,"M 4.1 - 25 km NW of Itháki, Greece",2024-09-02 08:00:00,38.549109,20.482100,eur,GRC,2024-09-27 14:51:32
41,WF,Wildfire in The Republic of North Macedonia 10...,2024-08-31 19:00:00,41.334022,21.641724,eur,MKD,2024-09-27 14:51:32
42,EQ,M 4.4 - Greenland Sea,2024-08-31 14:00:00,79.976209,1.253600,eur,NOR,2024-09-21 14:35:17
43,VO,"Reykjanes Volcano, Iceland",2024-08-29 00:00:00,63.866009,-22.717000,eur,ISL,2024-09-27 14:51:32
44,EQ,"M 5.1 - 107 km WNW of Höfn, Iceland",2024-09-03 16:00:00,64.612209,-17.322400,eur,ISL,2024-09-27 14:51:32
45,EQ,"M 4.1 - 25 km NW of Itháki, Greece",2024-09-02 08:00:00,38.549109,20.482100,eur,GRC,2024-09-27 14:51:32
46,WF,Wildfire in The Republic of North Macedonia 10...,2024-08-31 19:00:00,41.334022,21.641724,eur,MKD,2024-09-27 14:51:32
47,EQ,M 4.4 - Greenland Sea,2024-08-31 14:00:00,79.976209,1.253600,eur,NOR,2024-09-21 14:35:17
48,VO,"Reykjanes Volcano, Iceland",2024-08-29 00:00:00,63.866009,-22.717000,eur,ISL,2024-09-27 14:51:32

In [25]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=AUS&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df7 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df7

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,TC,Tropical Cyclone JEBI-24,2024-09-27 12:00:00,17.200736,146.800000,aus,MNP,2024-09-27 14:51:24
1,Misc,"Burn Off, ERANGY SPRING RD",2024-09-27 11:00:00,-28.871280,115.282992,aus,AUS,2024-09-27 14:51:24
2,Misc,"Burn Off, WINTERGREENE DR",2024-09-27 10:00:00,-31.856209,115.932462,aus,AUS,2024-09-27 14:51:24
3,DR,Drought in Australia,2024-09-27 09:00:00,-35.931000,140.238391,aus,AUS,2024-09-27 14:51:24
4,Misc,"Burn Off, POWELL RD",2024-09-27 09:00:00,-32.553924,115.791878,aus,AUS,2024-09-27 14:51:24
...,...,...,...,...,...,...,...,...
215,TC,Tropical Cyclone SHANSHAN-24,2024-08-29 18:00:00,17.000000,142.800000,aus,MNP,2024-08-30 02:35:00
216,Misc,"Fire, MARDIWAH LOOP",2024-08-29 09:00:00,-18.212351,127.654030,aus,AUS,2024-08-29 14:36:53
217,SW,"Storm Advice, Rocky Gully, Western Australia",2024-08-29 08:00:00,-34.513530,117.010200,aus,AUS,2024-08-29 14:36:53
218,VO,"Yasur Volcano, Vanuatu",2024-08-29 00:00:00,-19.482991,169.447000,aus,VUT,2024-09-27 14:51:24
219,WF,Wildfire in Australia 1021936,2024-08-28 19:00:00,-13.311797,135.662717,aus,AUS,2024-09-27 14:51:24

In [26]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 2):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=OCEAN&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df8 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df8

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,TC,Tropical Cyclone ISAAC-24,2024-09-27 09:00:00,38.800736,-42.400000,ocean,PRT,2024-09-27 14:51:22
1,EQ,Earthquake in,2024-09-26 19:00:00,-17.187500,66.069791,ocean,MUS,2024-09-27 14:51:22
2,EQ,M 5.4 - Mauritius - Reunion region,2024-09-22 20:00:00,-17.315291,66.498300,ocean,MUS,2024-09-27 14:51:22
3,EQ,M 5.1 - South Indian Ocean,2024-09-19 10:00:00,-5.554591,82.621800,ocean,IOT,2024-09-27 14:51:22
4,EQ,M 4.9 - southern Mid-Atlantic Ridge,2024-09-17 17:00:00,-24.510391,-13.600500,ocean,SHN,2024-09-27 14:51:22
5,TC,Tropical Cyclone GORDON-24,2024-09-17 09:00:00,27.600000,-44.600000,ocean,PRT,2024-09-17 14:35:21
6,EQ,Earthquake in,2024-09-10 23:00:00,-55.804167,-25.196055,ocean,SGS,2024-09-11 22:36:03
7,EQ,M 5.0 - Mid-Indian Ridge,2024-09-09 06:00:00,-22.451091,69.220800,ocean,MUS,2024-09-27 14:51:22
8,EQ,MID-INDIAN RIDGE,2024-09-09 06:00:00,-22.500100,69.220800,ocean,MUS,2024-09-11 22:36:03
9,EQ,M 4.5 - northern Mid-Atlantic Ridge,2024-09-01 17:00:00,31.209709,-40.883100,ocean,PRT,2024-09-27 14:51:22
10,EQ,M 4.8 - northern Mid-Atlantic Ridge,2024-09-01 15:00:00,26.432809,-44.579300,ocean,PRT,2024-09-27 14:51:22
11,EQ,M 4.6 - Mid-Indian Ridge,2024-09-01 01:00:00,-10.397891,66.382500,ocean,IOT,2024-09-27 14:51:22
12,EQ,M 4.6 - southern Mid-Atlantic Ridge,2024-08-29 17:00:00,-41.592891,-16.414300,ocean,SGS,2024-09-27 14:51:22

In [29]:
print(type(data))
print(type(df))
print(type(df1))
print(type(df2))
print(type(df3))
print(type(df4))
print(type(df5))
print(type(df6))
print(type(df7))
print(type(df8))

<class 'str'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [33]:
disaster = pd.concat([df, df1,df3,df2, df4, df5, df6, df7, df8], axis=0, ignore_index=True)
disaster.to_csv("disaster2_data.csv", index=False)