In [1]:
import pandas as pd
import requests

In [17]:
response = requests.get("https://api.ambeedata.com/weather/forecast/by-lat-lng?lat=12&lng=77&filter=hourly&x-api-key=09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477")
response

In [18]:
response.json()

{'message': 'success',
 'data': {'lat': 12,
  'lng': 77,
  'forecast': [{'timezone': 'Asia/Kolkata',
    'time': 1725552000,
    'apparentTemperature': 71,
    'cloudCover': 0.74,
    'dewPoint': 66.62,
    'humidity': 85,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 71,
    'visibility': 10,
    'windGust': 18.85,
    'ozone': 273.68,
    'uvIndex': 0,
    'windSpeed': 8.57,
    'windBearing': 260,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725555600,
    'apparentTemperature': 70,
    'cloudCover': 0.93,
    'dewPoint': 66.65,
    'humidity': 87,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 70,
    'visibility': 10,
    'windGust': 16.83,
    'ozone': 273.8,
    'uvIndex': 0,
    'windSpeed': 7.17,
    'windBearing': 257,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725559200,
    'apparentTemperature': 69,
    'cloudCover': 1,
    'dewPoint': 63.36,
    'humidity': 80,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 69,
    'visibility': 10,
    'windGust': 18.6,
    'ozone': 271.8,
    'uvIndex': 0,
    'windSpeed': 6.71,
    'windBearing': 263,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725562800,
    'apparentTemperature': 69,
    'cloudCover': 1,
    'dewPoint': 66.35,
    'humidity': 90,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 69,
    'visibility': 10,
    'windGust': 17.04,
    'ozone': 271.24,
    'uvIndex': 0,
    'windSpeed': 6.12,
    'windBearing': 251,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725566400,
    'apparentTemperature': 68,
    'cloudCover': 1,
    'dewPoint': 63.95,
    'humidity': 86,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 68,
    'visibility': 10,
    'windGust': 18.86,
    'ozone': 271.51,
    'uvIndex': 0,
    'windSpeed': 6.82,
    'windBearing': 264,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725570000,
    'apparentTemperature': 67,
    'cloudCover': 0.81,
    'dewPoint': 64.17,
    'humidity': 88,
    'pressure': 1009,
    'precipIntensity': 0,
    'temperature': 68,
    'visibility': 10,
    'windGust': 19.49,
    'ozone': 271.78,
    'uvIndex': 0,
    'windSpeed': 6.35,
    'windBearing': 259,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725573600,
    'apparentTemperature': 67,
    'cloudCover': 0.64,
    'dewPoint': 64.22,
    'humidity': 89,
    'pressure': 1009,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 17.45,
    'ozone': 271.8,
    'uvIndex': 0,
    'windSpeed': 5.45,
    'windBearing': 254,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725577200,
    'apparentTemperature': 68,
    'cloudCover': 1,
    'dewPoint': 65.01,
    'humidity': 88,
    'pressure': 1009,
    'precipIntensity': 0,
    'temperature': 68,
    'visibility': 10,
    'windGust': 16.58,
    'ozone': 271.03,
    'uvIndex': 0,
    'windSpeed': 5.58,
    'windBearing': 264,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725580800,
    'apparentTemperature': 67,
    'cloudCover': 0.38,
    'dewPoint': 64.13,
    'humidity': 88,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 17.25,
    'ozone': 272.37,
    'uvIndex': 0,
    'windSpeed': 5.08,
    'windBearing': 244,
    'icon': 'clear',
    'summary': 'Clear skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725584400,
    'apparentTemperature': 67,
    'cloudCover': 0.94,
    'dewPoint': 64.04,
    'humidity': 88,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 17.93,
    'ozone': 273.32,
    'uvIndex': 0.08,
    'windSpeed': 4.58,
    'windBearing': 246,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725588000,
    'apparentTemperature': 70,
    'cloudCover': 1,
    'dewPoint': 64.31,
    'humidity': 80,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 70,
    'visibility': 10,
    'windGust': 17.9,
    'ozone': 274.42,
    'uvIndex': 0.71,
    'windSpeed': 7.09,
    'windBearing': 253,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725591600,
    'apparentTemperature': 73,
    'cloudCover': 1,
    'dewPoint': 64.58,
    'humidity': 73,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 73,
    'visibility': 10,
    'windGust': 17,
    'ozone': 274.27,
    'uvIndex': 1.98,
    'windSpeed': 9.46,
    'windBearing': 265,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725595200,
    'apparentTemperature': 76,
    'cloudCover': 1,
    'dewPoint': 64.48,
    'humidity': 66,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 76,
    'visibility': 10,
    'windGust': 16.65,
    'ozone': 274.99,
    'uvIndex': 3.79,
    'windSpeed': 11.09,
    'windBearing': 265,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. Moderate UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725598800,
    'apparentTemperature': 79,
    'cloudCover': 1,
    'dewPoint': 64.34,
    'humidity': 60,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 79,
    'visibility': 10,
    'windGust': 17.04,
    'ozone': 275.34,
    'uvIndex': 5.04,
    'windSpeed': 12.06,
    'windBearing': 268,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. High UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725602400,
    'apparentTemperature': 81,
    'cloudCover': 1,
    'dewPoint': 64.67,
    'humidity': 59,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 80,
    'visibility': 10,
    'windGust': 17.72,
    'ozone': 270.45,
    'uvIndex': 8.31,
    'windSpeed': 12.93,
    'windBearing': 276,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. High UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725606000,
    'apparentTemperature': 82,
    'cloudCover': 1,
    'dewPoint': 64.34,
    'humidity': 56,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 81,
    'visibility': 10,
    'windGust': 17.68,
    'ozone': 269.99,
    'uvIndex': 9.32,
    'windSpeed': 13.41,
    'windBearing': 276,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. High UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725609600,
    'apparentTemperature': 84,
    'cloudCover': 1,
    'dewPoint': 64.13,
    'humidity': 53,
    'pressure': 1008,
    'precipIntensity': 0,
    'temperature': 82,
    'visibility': 10,
    'windGust': 18.35,
    'ozone': 269.04,
    'uvIndex': 7.36,
    'windSpeed': 14.35,
    'windBearing': 278,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. High UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725613200,
    'apparentTemperature': 83,
    'cloudCover': 1,
    'dewPoint': 64.13,
    'humidity': 53,
    'pressure': 1008,
    'precipIntensity': 0,
    'temperature': 82,
    'visibility': 10,
    'windGust': 17.91,
    'ozone': 268.11,
    'uvIndex': 5.44,
    'windSpeed': 13.16,
    'windBearing': 281,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. High UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725616800,
    'apparentTemperature': 83,
    'cloudCover': 1,
    'dewPoint': 64.85,
    'humidity': 56,
    'pressure': 1007,
    'precipIntensity': 0,
    'temperature': 82,
    'visibility': 10,
    'windGust': 17.08,
    'ozone': 267.27,
    'uvIndex': 3.14,
    'windSpeed': 12.21,
    'windBearing': 274,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. Moderate UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725620400,
    'apparentTemperature': 79,
    'cloudCover': 1,
    'dewPoint': 65.75,
    'humidity': 62,
    'pressure': 1007,
    'precipIntensity': 0.04,
    'temperature': 79,
    'visibility': 10,
    'windGust': 17.34,
    'ozone': 267.98,
    'uvIndex': 1.12,
    'windSpeed': 11.92,
    'windBearing': 262,
    'icon': 'rain',
    'summary': 'Expect some rain. Temperatures will feel warm. Moderate humidity. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725624000,
    'apparentTemperature': 79,
    'cloudCover': 1,
    'dewPoint': 66.29,
    'humidity': 64,
    'pressure': 1008,
    'precipIntensity': 0.15,
    'temperature': 79,
    'visibility': 10,
    'windGust': 17,
    'ozone': 268.56,
    'uvIndex': 0.22,
    'windSpeed': 11.83,
    'windBearing': 257,
    'icon': 'rain',
    'summary': 'Expect some rain. Temperatures will feel warm. Moderate humidity. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725627600,
    'apparentTemperature': 75,
    'cloudCover': 1,
    'dewPoint': 66.29,
    'humidity': 72,
    'pressure': 1009,
    'precipIntensity': 0,
    'temperature': 75,
    'visibility': 10,
    'windGust': 21.28,
    'ozone': 268.47,
    'uvIndex': 0,
    'windSpeed': 12.47,
    'windBearing': 257,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725631200,
    'apparentTemperature': 73,
    'cloudCover': 1,
    'dewPoint': 66.47,
    'humidity': 77,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 73,
    'visibility': 10,
    'windGust': 20.46,
    'ozone': 269.04,
    'uvIndex': 0,
    'windSpeed': 10.5,
    'windBearing': 258,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725634800,
    'apparentTemperature': 72,
    'cloudCover': 1,
    'dewPoint': 66.34,
    'humidity': 81,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 72,
    'visibility': 10,
    'windGust': 19.57,
    'ozone': 269.44,
    'uvIndex': 0,
    'windSpeed': 9.61,
    'windBearing': 258,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Windy conditions. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725638400,
    'apparentTemperature': 71,
    'cloudCover': 1,
    'dewPoint': 66.47,
    'humidity': 84,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 71,
    'visibility': 10,
    'windGust': 18.35,
    'ozone': 270.94,
    'uvIndex': 0,
    'windSpeed': 8.05,
    'windBearing': 258,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725642000,
    'apparentTemperature': 71,
    'cloudCover': 0.99,
    'dewPoint': 65.87,
    'humidity': 84,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 71,
    'visibility': 10,
    'windGust': 20.59,
    'ozone': 271.31,
    'uvIndex': 0,
    'windSpeed': 9.03,
    'windBearing': 262,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725645600,
    'apparentTemperature': 70,
    'cloudCover': 0.85,
    'dewPoint': 65.57,
    'humidity': 85,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 70,
    'visibility': 10,
    'windGust': 18.92,
    'ozone': 270.66,
    'uvIndex': 0,
    'windSpeed': 7.48,
    'windBearing': 264,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725649200,
    'apparentTemperature': 69,
    'cloudCover': 0.59,
    'dewPoint': 65.21,
    'humidity': 86,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 69,
    'visibility': 10,
    'windGust': 18.61,
    'ozone': 270.25,
    'uvIndex': 0,
    'windSpeed': 7.1,
    'windBearing': 264,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725652800,
    'apparentTemperature': 69,
    'cloudCover': 0.54,
    'dewPoint': 64.56,
    'humidity': 85,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 69,
    'visibility': 10,
    'windGust': 18.15,
    'ozone': 270.18,
    'uvIndex': 0,
    'windSpeed': 6.45,
    'windBearing': 265,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725656400,
    'apparentTemperature': 68,
    'cloudCover': 0.52,
    'dewPoint': 63.77,
    'humidity': 84,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 68,
    'visibility': 10,
    'windGust': 18.57,
    'ozone': 270.86,
    'uvIndex': 0,
    'windSpeed': 5.95,
    'windBearing': 261,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725660000,
    'apparentTemperature': 68,
    'cloudCover': 0.41,
    'dewPoint': 63.17,
    'humidity': 84,
    'pressure': 1010,
    'precipIntensity': 0,
    'temperature': 68,
    'visibility': 10,
    'windGust': 17.52,
    'ozone': 271.49,
    'uvIndex': 0,
    'windSpeed': 5.04,
    'windBearing': 254,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725663600,
    'apparentTemperature': 67,
    'cloudCover': 0.66,
    'dewPoint': 63.23,
    'humidity': 85,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 15.22,
    'ozone': 272.54,
    'uvIndex': 0,
    'windSpeed': 4.47,
    'windBearing': 263,
    'icon': 'partly-cloudy',
    'summary': 'Partly cloudy skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725667200,
    'apparentTemperature': 67,
    'cloudCover': 0.85,
    'dewPoint': 63.41,
    'humidity': 87,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 12.14,
    'ozone': 272.64,
    'uvIndex': 0,
    'windSpeed': 4.09,
    'windBearing': 266,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725670800,
    'apparentTemperature': 67,
    'cloudCover': 1,
    'dewPoint': 63.85,
    'humidity': 88,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 67,
    'visibility': 10,
    'windGust': 16.15,
    'ozone': 273.52,
    'uvIndex': 0.06,
    'windSpeed': 4.58,
    'windBearing': 259,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. A mild day ahead. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725674400,
    'apparentTemperature': 69,
    'cloudCover': 1,
    'dewPoint': 64.13,
    'humidity': 82,
    'pressure': 1013,
    'precipIntensity': 0,
    'temperature': 69,
    'visibility': 10,
    'windGust': 18.22,
    'ozone': 274.1,
    'uvIndex': 0.56,
    'windSpeed': 7.16,
    'windBearing': 263,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725678000,
    'apparentTemperature': 72,
    'cloudCover': 1,
    'dewPoint': 63.62,
    'humidity': 73,
    'pressure': 1013,
    'precipIntensity': 0,
    'temperature': 72,
    'visibility': 10,
    'windGust': 14.79,
    'ozone': 274.11,
    'uvIndex': 1.7,
    'windSpeed': 8.78,
    'windBearing': 270,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Higher humidity levels. Expect a gentle breeze. Low UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725681600,
    'apparentTemperature': 75,
    'cloudCover': 1,
    'dewPoint': 63.23,
    'humidity': 65,
    'pressure': 1013,
    'precipIntensity': 0,
    'temperature': 75,
    'visibility': 10,
    'windGust': 15.21,
    'ozone': 274.5,
    'uvIndex': 3.3,
    'windSpeed': 10.02,
    'windBearing': 268,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. Moderate UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725685200,
    'apparentTemperature': 79,
    'cloudCover': 0.9,
    'dewPoint': 63.41,
    'humidity': 59,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 79,
    'visibility': 10,
    'windGust': 18.19,
    'ozone': 273.67,
    'uvIndex': 4.36,
    'windSpeed': 12.67,
    'windBearing': 268,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. Moderate UV levels.'},
   {'timezone': 'Asia/Kolkata',
    'time': 1725688800,
    'apparentTemperature': 82,
    'cloudCover': 0.81,
    'dewPoint': 63.23,
    'humidity': 54,
    'pressure': 1012,
    'precipIntensity': 0,
    'temperature': 81,
    'visibility': 10,
    'windGust': 18.58,
    'ozone': 272.58,
    'windSpeed': 14.06,
    'windBearing': 273,
    'icon': 'cloudy',
    'summary': 'Cloudy skies. Temperatures will feel warm. Moderate humidity. Windy conditions. '},
   {'timezone': 'Asia/Kolkata',
    'time': 1725692400,
    'apparentTemperature': 82,
    'cloudCover': 1,
    'dewPoint': 63.05,
    'humidity': 54,
    'pressure': 1011,
    'precipIntensity': 0,
    'temperature': 81,
    'visibility': 10,
    'windGust': 20.17,
    'ozone': 273.36,
    'uvIndex': 8.53,
    'windSpeed': 14.99,
    'windBearing': 277,
    'icon': 'cloudy',

In [45]:
# import http.client

# conn = http.client.HTTPSConnection("api.ambeedata.com")

# headers = {
#     'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
#     'Content-type': "application/json"
#     }

# conn.request("GET", "/disasters/latest/by-country-code?countryCode=IND&limit=50&page=1", headers=headers)

# res = conn.getresponse()
# data = res.read()

# data.decode("utf-8")

In [43]:
# import http.client

# conn = http.client.HTTPSConnection("api.ambeedata.com")

# headers = {
#     'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
#     'Content-type': "application/json"
#     }

# conn.request("GET", "/disasters/latest/by-country-code?countryCode=IND&limit=50&page=2", headers=headers)

# res = conn.getresponse()
# data = res.read()

# data.decode("utf-8")

In [42]:
# import http.client

# conn = http.client.HTTPSConnection("api.ambeedata.com")

# headers = {
#     'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
#     'Content-type': "application/json"
#     }

# conn.request("GET", "/disasters/latest/by-country-code?countryCode=USA&limit=50&page=2", headers=headers)

# res = conn.getresponse()
# data = res.read()

# data.decode("utf-8")

### Continent to search for events. Can be should be one of AFR, ANT, ASIA, AUS, EUR, NAR, SAR, OCEAN

In [1]:
import http.client


conn = http.client.HTTPSConnection("api.ambeedata.com")

headers = {
    'x-api-key': "08af8b0cedf4f975507cb122476f0d32846546b9a06b4b5688e2632197afb32c",
    'Content-type': "application/json"
    }

conn.request("GET", "/disasters/latest/by-continent?continent=NAR&limit=50&page=1", headers=headers)

In [2]:
res = conn.getresponse()
data = res.read()
data = data.decode("utf-8")
json_data = json.loads(data)

NameError: name 'json' is not defined

In [15]:
json_data

{'message': 'success',
 'hasNextPage': True,
 'page': 1,
 'limit': 50,
 'result': [{'event_type': 'EQ',
   'event_name': 'NORTHERN ALASKA',
   'date': '2024-09-05 12:00:00',
   'lat': 65.8812,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -152.2179,
   'source_event_id': '11881331',
   'event_id': '66c703fd72c3d1a4e41443e0'},
  {'event_type': 'DR',
   'event_name': 'Drought in Guatemala, Honduras, Mexico, Nicaragua',
   'date': '2024-09-05 00:00:00',
   'lat': 18.5,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-05 14:35:56',
   'lng': -99,
   'source_event_id': '1016963',
   'event_id': '66c703f672c3d1a4e413d41a'},
  {'event_type': 'DR',
   'event_name': 'Drought in Canada',
   'date': '2024-09-05 00:00:00',
   'lat': 53.5,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-05 14:35:56',
   'lng': -116,
   'source_event_id': '1017111',
   'event_id': '66c703f672c3d1a4e413d420'},
  {'event_type': 'EQ',
   'event_name': 'CALIFORNIA-NEVADA BORDER REGION',
   'date': '2024-09-04 11:00:00',
   'lat': 36.5233,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -115.54,
   'source_event_id': '11880832',
   'event_id': '66c7040272c3d1a4e41490a5'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL CALIFORNIA',
   'date': '2024-09-04 11:00:00',
   'lat': 37.2825,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -119.999,
   'source_event_id': '11880986',
   'event_id': '66d91908bb7a6d672691817d'},
  {'event_type': 'EQ',
   'event_name': 'NEVADA',
   'date': '2024-09-04 10:00:00',
   'lat': 38.1864,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -116.7175,
   'source_event_id': '11880831',
   'event_id': '66c7040c72c3d1a4e4152750'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL CALIFORNIA',
   'date': '2024-09-04 02:00:00',
   'lat': 37.715,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -122.542336,
   'source_event_id': '11880741',
   'event_id': '66c7043372c3d1a4e41798bd'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-04 02:00:00',
   'lat': 48.046167,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -114.061667,
   'source_event_id': '11880754',
   'event_id': '66c7043972c3d1a4e417ff98'},
  {'event_type': 'EQ',
   'event_name': 'CALIFORNIA-NEVADA BORDER REGION',
   'date': '2024-09-04 01:00:00',
   'lat': 36.4477,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -115.3007,
   'source_event_id': '11880731',
   'event_id': '66c703c372c3d1a4e410aa62'},
  {'event_type': 'EQ',
   'event_name': 'SOUTHERN TEXAS',
   'date': '2024-09-03 21:00:00',
   'lat': 28.575,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -98.445,
   'source_event_id': '11880658',
   'event_id': '66d47e40bb7a6d672626e02e'},
  {'event_type': 'EQ',
   'event_name': 'OREGON',
   'date': '2024-09-03 20:00:00',
   'lat': 42.1375,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -119.028167,
   'source_event_id': '11880649',
   'event_id': '66c704e672c3d1a4e422b44a'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-03 19:00:00',
   'lat': 45.370333,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -112.592,
   'source_event_id': '11880630',
   'event_id': '66d7c7a2bb7a6d672672d690'},
  {'event_type': 'EQ',
   'event_name': 'OKLAHOMA',
   'date': '2024-09-03 15:00:00',
   'lat': 36.230667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -95.839167,
   'source_event_id': '11880889',
   'event_id': '66c703c372c3d1a4e410a89f'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-03 13:00:00',
   'lat': 63.3525,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -152.6917,
   'source_event_id': '11880474',
   'event_id': '66c7041b72c3d1a4e41616d2'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-03 11:00:00',
   'lat': 47.791833,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -114.357333,
   'source_event_id': '11880558',
   'event_id': '66c9eff0bb7a6d6726331337'},
  {'event_type': 'EQ',
   'event_name': 'M 4.4 - 8 km S of San José del Cabo, Mexico',
   'date': '2024-09-03 11:00:00',
   'lat': 23.02420857016478,
   'continent': 'nar',
   'country_code': 'MEX',
   'created_time': '2024-09-05 14:35:56',
   'lng': -109.717,
   'source_event_id': 'us6000nph0',
   'event_id': '66d71f20bb7a6d67266344f9'},
  {'event_type': 'EQ',
   'event_name': 'YELLOWSTONE REGION, WYOMING',
   'date': '2024-09-03 09:00:00',
   'lat': 44.688167,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -110.4525,
   'source_event_id': '11880481',
   'event_id': '66c703c572c3d1a4e410cf6d'},
  {'event_type': 'EQ',
   'event_name': 'WASHINGTON',
   'date': '2024-09-03 09:00:00',
   'lat': 46.2905,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -122.165,
   'source_event_id': '11880551',
   'event_id': '66c703f272c3d1a4e41393bf'},
  {'event_type': 'EQ',
   'event_name': 'UTAH',
   'date': '2024-09-03 08:00:00',
   'lat': 39.566833,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -111.214,
   'source_event_id': '11880524',
   'event_id': '66c7042472c3d1a4e416a7aa'},
  {'event_type': 'EQ',
   'event_name': 'OREGON',
   'date': '2024-09-03 07:00:00',
   'lat': 43.716333,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -121.234833,
   'source_event_id': '11880923',
   'event_id': '66c703cd72c3d1a4e4114188'},
  {'event_type': 'EQ',
   'event_name': 'SOUTHERN ALASKA',
   'date': '2024-09-03 07:00:00',
   'lat': 61.4526,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -146.1767,
   'source_event_id': '11880415',
   'event_id': '66c7041b72c3d1a4e4161759'},
  {'event_type': 'EQ',
   'event_name': 'ALABAMA',
   'date': '2024-09-03 06:00:00',
   'lat': 34.883833,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -85.036167,
   'source_event_id': '11880462',
   'event_id': '66c703eb72c3d1a4e4131d3e'},
  {'event_type': 'EQ',
   'event_name': 'MONTANA',
   'date': '2024-09-03 05:00:00',
   'lat': 46.827667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -112.3825,
   'source_event_id': '11880473',
   'event_id': '66c703c472c3d1a4e410be6a'},
  {'event_type': 'EQ',
   'event_name': 'EASTERN IDAHO',
   'date': '2024-09-03 05:00:00',
   'lat': 44.627333,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -112.606667,
   'source_event_id': '11880469',
   'event_id': '66c7045272c3d1a4e419a370'},
  {'event_type': 'EQ',
   'event_name': 'OKLAHOMA',
   'date': '2024-09-03 04:00:00',
   'lat': 36.695667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -97.674167,
   'source_event_id': '11880918',
   'event_id': '66c703c872c3d1a4e410f7d1'},
  {'event_type': 'EQ',
   'event_name': 'UTAH',
   'date': '2024-09-03 04:00:00',
   'lat': 38.493667,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -112.879833,
   'source_event_id': '11880542',
   'event_id': '66c7041b72c3d1a4e41617d2'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-02 15:00:00',
   'lat': 64.9043,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -149.1394,
   'source_event_id': '11880223',
   'event_id': '66c703c372c3d1a4e410acfd'},
  {'event_type': 'EQ',
   'event_name': 'SOUTHERN ALASKA',
   'date': '2024-09-02 13:00:00',
   'lat': 60.4365,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -145.7364,
   'source_event_id': '11880183',
   'event_id': '66c7042e72c3d1a4e4173b48'},
  {'event_type': 'WF',
   'event_name': 'SYRUP Wildfire, Elmore, Idaho',
   'date': '2024-09-02 12:00:00',
   'lat': 43.26927957016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -115.672065,
   'source_event_id': 'EONET_10768',
   'event_id': '66d675e5bb7a6d672653b3db'},
  {'event_type': 'EQ',
   'event_name': 'M 4.8 - off the coast of Central America',
   'date': '2024-09-02 11:00:00',
   'lat': 3.28030857016478,
   'continent': 'nar',
   'country_code': 'PAN',
   'created_time': '2024-09-05 14:35:56',
   'lng': -84.1767,
   'source_event_id': 'us6000np8s',
   'event_id': '66d5cd70bb7a6d672644d44a'},
  {'date': '2024-09-02 11:00:00',
   'lat': 33.715167,
   'event_name': 'SOUTHERN CALIFORNIA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -118.618833,
   'source_event_id': '11880163',
   'event_id': '66d5cd73bb7a6d672644eb76'},
  {'event_type': 'EQ',
   'event_name': 'VANCOUVER ISLAND, CANADA REGION',
   'date': '2024-09-02 07:00:00',
   'lat': 48.441502,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-04 14:34:58',
   'lng': -123.448997,
   'source_event_id': '11880207',
   'event_id': '66c946f74e6e6f71509cfc9c'},
  {'event_type': 'EQ',
   'event_name': 'WASHINGTON',
   'date': '2024-09-02 04:00:00',
   'lat': 47.579,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -120.287333,
   'source_event_id': '11880577',
   'event_id': '66c703cd72c3d1a4e41140da'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL CALIFORNIA',
   'date': '2024-09-02 02:00:00',
   'lat': 36.467167,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -121.043999,
   'source_event_id': '11880049',
   'event_id': '66cd3b9fbb7a6d67267e3673'},
  {'event_type': 'EQ',
   'event_name': 'CENTRAL ALASKA',
   'date': '2024-09-02 00:00:00',
   'lat': 64.7852,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-04 14:34:58',
   'lng': -147.3752,
   'source_event_id': '11880022',
   'event_id': '66c703c472c3d1a4e410be41'},
  {'date': '2024-09-01 21:00:00',
   'lat': 62.2347,
   'event_name': 'CENTRAL ALASKA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -154.2832,
   'source_event_id': '11879984',
   'event_id': '66c703df72c3d1a4e4124a71'},
  {'event_type': 'SW',
   'event_name': 'Tropical Storm Hone',
   'date': '2024-09-01 18:00:00',
   'lat': 26.14900857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -179.8,
   'source_event_id': 'EONET_10419',
   'event_id': '66d5247bbb7a6d672635b73e'},
  {'date': '2024-09-01 17:00:00',
   'lat': 47.689,
   'event_name': 'NEAR COAST OF WASHINGTON',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -124.039333,
   'source_event_id': '11880389',
   'event_id': '66c703f172c3d1a4e4138525'},
  {'date': '2024-09-01 12:00:00',
   'lat': 40.787834,
   'event_name': 'NORTHERN CALIFORNIA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -123.554001,
   'source_event_id': '11879879',
   'event_id': '66c703c572c3d1a4e410cf0b'},
  {'event_type': 'EQ',
   'event_name': 'M 2.9 - 6 km ENE of Capulin, New Mexico',
   'date': '2024-09-01 11:00:00',
   'lat': 36.30310857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -106.734,
   'source_event_id': 'us6000np1x',
   'event_id': '66d5cd77bb7a6d6726451381'},
  {'event_type': 'EQ',
   'event_name': 'M 3.8 - 5 km SE of Pierreville, Canada',
   'date': '2024-09-01 09:00:00',
   'lat': 46.09280857016478,
   'continent': 'nar',
   'country_code': 'CAN',
   'created_time': '2024-09-05 14:35:56',
   'lng': -72.7553,
   'source_event_id': 'us6000np1d',
   'event_id': '66d47e3cbb7a6d672626bba6'},
  {'event_type': 'EQ',
   'event_name': 'M 3.5 - 31 km NE of Seeley Lake, Montana',
   'date': '2024-09-01 08:00:00',
   'lat': 47.39940857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -113.1597,
   'source_event_id': 'us6000np16',
   'event_id': '66d7c7a3bb7a6d672672ddc0'},
  {'date': '2024-09-01 06:00:00',
   'lat': 33.8355,
   'event_name': 'GEORGIA, USA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -82.147167,
   'source_event_id': '11879891',
   'event_id': '66d47e40bb7a6d672626e12d'},
  {'date': '2024-09-01 03:00:00',
   'lat': 40.6728,
   'event_name': 'NEW JERSEY',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-03 14:37:13',
   'lng': -74.7275,
   'source_event_id': '11879896',
   'event_id': '66c703c472c3d1a4e410bf0c'},
  {'date': '2024-08-31 22:00:00',
   'lat': 34.379333,
   'event_name': 'SOUTHERN CALIFORNIA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-02 14:36:30',
   'lng': -119.928667,
   'source_event_id': '11879724',
   'event_id': '66c703c372c3d1a4e410ab78'},
  {'date': '2024-08-31 21:00:00',
   'lat': 58.7432,
   'event_name': 'SOUTHEASTERN ALASKA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-02 14:36:30',
   'lng': -137.5187,
   'source_event_id': '11879712',
   'event_id': '66d3d414bb7a6d6726176813'},
  {'event_type': 'EQ',
   'event_name': 'M 2.7 - 25 km WSW of Lander, Wyoming',
   'date': '2024-08-31 18:00:00',
   'lat': 42.79930857016478,
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-05 14:35:56',
   'lng': -109.0215,
   'source_event_id': 'us6000nnwn',
   'event_id': '66d3d411bb7a6d6726174cb8'},
  {'date': '2024-08-31 15:00:00',
   'lat': 66.1462,
   'event_name': 'NORTHERN ALASKA',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-02 14:36:30',
   'lng': -147.8202,
   'source_event_id': '11879662',
   'event_id': '66d3d414bb7a6d672617693d'},
  {'date': '2024-08-31 12:00:00',
   'lat': 38.7255,
   'event_name': 'KENTUCKY',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-02 14:36:30',
   'lng': -83.6315,
   'source_event_id': '11879888',
   'event_id': '66d47e41bb7a6d672626e505'},
  {'date': '2024-08-31 09:00:00',
   'lat': 35.324,
   'event_name': 'ARKANSAS',
   'event_type': 'EQ',
   'continent': 'nar',
   'country_code': 'USA',
   'created_time': '2024-09-02 14:36:30',
   'lng': -92.660167,
   'source_event_id': '11879637',
   'event_id': '66c7040272c3d1a4e41490d1'}]}

In [16]:
data = pd.DataFrame(json_data['result'])[['event_type','event_name','date','lat','lng','continent','country_code','created_time']]
data

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,NORTHERN ALASKA,2024-09-05 12:00:00,65.881200,-152.217900,nar,USA,2024-09-05 14:35:56
1,DR,"Drought in Guatemala, Honduras, Mexico, Nicaragua",2024-09-05 00:00:00,18.500000,-99.000000,nar,MEX,2024-09-05 14:35:56
2,DR,Drought in Canada,2024-09-05 00:00:00,53.500000,-116.000000,nar,CAN,2024-09-05 14:35:56
3,EQ,CALIFORNIA-NEVADA BORDER REGION,2024-09-04 11:00:00,36.523300,-115.540000,nar,USA,2024-09-05 14:35:56
4,EQ,CENTRAL CALIFORNIA,2024-09-04 11:00:00,37.282500,-119.999000,nar,USA,2024-09-05 14:35:56
5,EQ,NEVADA,2024-09-04 10:00:00,38.186400,-116.717500,nar,USA,2024-09-04 14:34:58
6,EQ,CENTRAL CALIFORNIA,2024-09-04 02:00:00,37.715000,-122.542336,nar,USA,2024-09-05 14:35:56
7,EQ,MONTANA,2024-09-04 02:00:00,48.046167,-114.061667,nar,USA,2024-09-05 14:35:56
8,EQ,CALIFORNIA-NEVADA BORDER REGION,2024-09-04 01:00:00,36.447700,-115.300700,nar,USA,2024-09-05 14:35:56
9,EQ,SOUTHERN TEXAS,2024-09-03 21:00:00,28.575000,-98.445000,nar,USA,2024-09-05 14:35:56
10,EQ,OREGON,2024-09-03 20:00:00,42.137500,-119.028167,nar,USA,2024-09-05 14:35:56
11,EQ,MONTANA,2024-09-03 19:00:00,45.370333,-112.592000,nar,USA,2024-09-05 14:35:56
12,EQ,OKLAHOMA,2024-09-03 15:00:00,36.230667,-95.839167,nar,USA,2024-09-05 14:35:56
13,EQ,CENTRAL ALASKA,2024-09-03 13:00:00,63.352500,-152.691700,nar,USA,2024-09-05 14:35:56
14,EQ,MONTANA,2024-09-03 11:00:00,47.791833,-114.357333,nar,USA,2024-09-05 14:35:56
15,EQ,"M 4.4 - 8 km S of San José del Cabo, Mexico",2024-09-03 11:00:00,23.024209,-109.717000,nar,MEX,2024-09-05 14:35:56
16,EQ,"YELLOWSTONE REGION, WYOMING",2024-09-03 09:00:00,44.688167,-110.452500,nar,USA,2024-09-05 14:35:56
17,EQ,WASHINGTON,2024-09-03 09:00:00,46.290500,-122.165000,nar,USA,2024-09-05 14:35:56
18,EQ,UTAH,2024-09-03 08:00:00,39.566833,-111.214000,nar,USA,2024-09-05 14:35:56
19,EQ,OREGON,2024-09-03 07:00:00,43.716333,-121.234833,nar,USA,2024-09-05 14:35:56
20,EQ,SOUTHERN ALASKA,2024-09-03 07:00:00,61.452600,-146.176700,nar,USA,2024-09-05 14:35:56
21,EQ,ALABAMA,2024-09-03 06:00:00,34.883833,-85.036167,nar,USA,2024-09-05 14:35:56
22,EQ,MONTANA,2024-09-03 05:00:00,46.827667,-112.382500,nar,USA,2024-09-05 14:35:56
23,EQ,EASTERN IDAHO,2024-09-03 05:00:00,44.627333,-112.606667,nar,USA,2024-09-05 14:35:56
24,EQ,OKLAHOMA,2024-09-03 04:00:00,36.695667,-97.674167,nar,USA,2024-09-05 14:35:56
25,EQ,UTAH,2024-09-03 04:00:00,38.493667,-112.879833,nar,USA,2024-09-05 14:35:56
26,EQ,CENTRAL ALASKA,2024-09-02 15:00:00,64.904300,-149.139400,nar,USA,2024-09-04 14:34:58
27,EQ,SOUTHERN ALASKA,2024-09-02 13:00:00,60.436500,-145.736400,nar,USA,2024-09-04 14:34:58
28,WF,"SYRUP Wildfire, Elmore, Idaho",2024-09-02 12:00:00,43.269280,-115.672065,nar,USA,2024-09-05 14:35:56
29,EQ,M 4.8 - off the coast of Central America,2024-09-02 11:00:00,3.280309,-84.176700,nar,PAN,2024-09-05 14:35:56
30,EQ,SOUTHERN CALIFORNIA,2024-09-02 11:00:00,33.715167,-118.618833,nar,USA,2024-09-03 14:37:13
31,EQ,"VANCOUVER ISLAND, CANADA REGION",2024-09-02 07:00:00,48.441502,-123.448997,nar,CAN,2024-09-04 14:34:58
32,EQ,WASHINGTON,2024-09-02 04:00:00,47.579000,-120.287333,nar,USA,2024-09-04 14:34:58
33,EQ,CENTRAL CALIFORNIA,2024-09-02 02:00:00,36.467167,-121.043999,nar,USA,2024-09-04 14:34:58
34,EQ,CENTRAL ALASKA,2024-09-02 00:00:00,64.785200,-147.375200,nar,USA,2024-09-04 14:34:58
35,EQ,CENTRAL ALASKA,2024-09-01 21:00:00,62.234700,-154.283200,nar,USA,2024-09-03 14:37:13
36,SW,Tropical Storm Hone,2024-09-01 18:00:00,26.149009,-179.800000,nar,USA,2024-09-05 14:35:56
37,EQ,NEAR COAST OF WASHINGTON,2024-09-01 17:00:00,47.689000,-124.039333,nar,USA,2024-09-03 14:37:13
38,EQ,NORTHERN CALIFORNIA,2024-09-01 12:00:00,40.787834,-123.554001,nar,USA,2024-09-03 14:37:13
39,EQ,"M 2.9 - 6 km ENE of Capulin, New Mexico",2024-09-01 11:00:00,36.303109,-106.734000,nar,USA,2024-09-05 14:35:56
40,EQ,"M 3.8 - 5 km SE of Pierreville, Canada",2024-09-01 09:00:00,46.092809,-72.755300,nar,CAN,2024-09-05 14:35:56
41,EQ,"M 3.5 - 31 km NE of Seeley Lake, Montana",2024-09-01 08:00:00,47.399409,-113.159700,nar,USA,2024-09-05 14:35:56
42,EQ,"GEORGIA, USA",2024-09-01 06:00:00,33.835500,-82.147167,nar,USA,2024-09-03 14:37:13
43,EQ,NEW JERSEY,2024-09-01 03:00:00,40.672800,-74.727500,nar,USA,2024-09-03 14:37:13
44,EQ,SOUTHERN CALIFORNIA,2024-08-31 22:00:00,34.379333,-119.928667,nar,USA,2024-09-02 14:36:30
45,EQ,SOUTHEASTERN ALASKA,2024-08-31 21:00:00,58.743200,-137.518700,nar,USA,2024-09-02 14:36:30
46,EQ,"M 2.7 - 25 km WSW of Lander, Wyoming",2024-08-31 18:00:00,42.799309,-109.021500,nar,USA,2024-09-05 14:35:56
47,EQ,NORTHERN ALASKA,2024-08-31 15:00:00,66.146200,-147.820200,nar,USA,2024-09-02 14:36:30
48,EQ,KENTUCKY,2024-08-31 12:00:00,38.725500,-83.631500,nar,USA,2024-09-02 14:36:30
49,EQ,ARKANSAS,2024-08-31 09:00:00,35.324000,-92.660167,nar,USA,2024-09-02 14:36:30

In [17]:
type(data)

pandas.core.frame.DataFrame

In [1]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 11):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=NAR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,NORTHERN ALASKA,2024-09-05 12:00:00,65.881200,-152.217900,nar,USA,2024-09-05 14:35:56
1,DR,"Drought in Guatemala, Honduras, Mexico, Nicaragua",2024-09-05 00:00:00,18.500000,-99.000000,nar,MEX,2024-09-05 14:35:56
2,DR,Drought in Canada,2024-09-05 00:00:00,53.500000,-116.000000,nar,CAN,2024-09-05 14:35:56
3,EQ,CALIFORNIA-NEVADA BORDER REGION,2024-09-04 11:00:00,36.523300,-115.540000,nar,USA,2024-09-05 14:35:56
4,EQ,CENTRAL CALIFORNIA,2024-09-04 11:00:00,37.282500,-119.999000,nar,USA,2024-09-05 14:35:56
...,...,...,...,...,...,...,...,...
482,WF,"Element Wildfire, Mohave, Arizona",2024-08-06 23:00:00,35.506642,-114.091450,nar,USA,2024-09-05 14:35:56
483,WF,Wildfire in Canada 1020976,2024-08-06 19:00:00,62.521045,-122.108018,nar,CAN,2024-09-05 14:35:56
484,WF,Wildfire in Canada 1021013,2024-08-06 19:00:00,61.156758,-126.345640,nar,CAN,2024-09-05 14:35:56
485,WF,Wildfire in Canada 1021011,2024-08-06 19:00:00,63.322478,-118.413773,nar,CAN,2024-09-05 14:35:56
486,EQ,"M 3.4 - 77 km W of The Bottom, Bonaire, Saint ...",2024-08-06 18:00:00,17.645175,-63.982833,nar,VIR,2024-09-05 14:35:56

In [84]:
type(df)

pandas.core.frame.DataFrame

In [64]:
df['country_code'].unique()

array(['USA', 'MEX', 'CAN', 'PAN', 'ATG', 'GRL', 'CRI', 'BRB', 'JAM',
       'AIA', 'TCA', 'BMU', 'FRA', 'CUB', 'HND', 'VIR'], dtype=object)

In [2]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 11):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ASIA&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df1 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df1

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,SW,Moderate Rain at Raipur,2024-09-05 14:00:00,21.986443,82.555254,asia,IND,2024-09-05 14:35:25
1,SW,Heavy Rain at Bhopal,2024-09-05 14:00:00,25.166010,78.424415,asia,IND,2024-09-05 14:35:25
2,SW,Moderate Rain at Raipur,2024-09-05 14:00:00,20.728024,81.139668,asia,IND,2024-09-05 14:35:25
3,SW,Lightning at SDMA,2024-09-05 14:00:00,15.111554,77.455062,asia,IND,2024-09-05 14:35:25
4,SW,Light Rain at Mumbai,2024-09-05 13:00:00,19.156937,74.855242,asia,IND,2024-09-05 14:35:25
...,...,...,...,...,...,...,...,...
495,EQ,Earthquake in Indonesia,2024-08-12 11:00:00,1.468599,124.808320,asia,IDN,2024-08-22 09:20:04
496,ET,Extremely Heavy Rain at Jaipur,2024-08-12 07:00:00,25.434251,75.738843,asia,IND,2024-08-22 09:20:04
497,EQ,"M 4.3 - 17 km SSW of Fasā, Iran",2024-08-12 06:00:00,28.851909,53.558300,asia,IRN,2024-09-05 14:35:25
498,EQ,"M 4.4 - 111 km SSE of Honchō, Japan",2024-08-12 05:00:00,41.210709,143.283200,asia,JPN,2024-09-05 14:35:25
499,FL,Flood in Malaysia,2024-08-12 01:00:00,4.800873,100.985607,asia,MYS,2024-08-22 09:20:08

In [61]:
df1['country_code'].unique()

array(['IND', 'BGD', 'JPN', 'PHL', 'HKG', 'AZE', 'RUS', 'TUR', 'CHN',
       'CYP', 'IDN', 'OMN', 'NPL', 'PAK', 'AFG', 'THA', 'KGZ', 'MYS',
       'KOR', 'SYR', 'IRN', 'VNM'], dtype=object)

In [3]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(11, 21):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ASIA&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df3 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df3

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,Misc,Moderate cloud to ground Lightning at Lucknow,2024-08-14 01:00:00,27.153928,82.402841,asia,IND,2024-08-22 09:20:12
1,TC,Tropical Cyclone WUKONG-24,2024-08-14 00:00:00,34.872677,147.737490,asia,JPN,2024-08-22 09:20:12
2,SW,Typhoon Ampil,2024-08-14 00:00:00,26.149009,140.300000,asia,JPN,2024-08-23 14:34:40
3,EQ,"M 4.6 - 77 km W of Sungai Penuh, Indonesia",2024-08-13 21:00:00,-2.064691,100.692800,asia,IDN,2024-09-05 14:35:25
4,EQ,"M 4.3 - 17 km SW of Nabire, Indonesia",2024-08-13 19:00:00,-3.529809,135.401300,asia,IDN,2024-09-05 14:35:25
...,...,...,...,...,...,...,...,...
108,TN,tsunami in JAPAN,2024-08-08 07:00:00,31.719000,131.527000,asia,JPN,2024-09-05 14:35:25
109,WF,Forest fires in Russian Federation,2024-08-08 00:00:00,63.252393,110.038171,asia,RUS,2024-08-22 09:19:38
110,EQ,"M 4.4 - 65 km NNE of Mawlaik, Myanmar",2024-08-07 13:00:00,24.219609,94.689200,asia,MMR,2024-09-05 14:35:25
111,SW,Heavy Rain at Dehradun,2024-08-07 09:00:00,30.963692,78.623655,asia,IND,2024-08-22 09:19:32
112,EQ,"M 4.3 - 94 km NNE of Namuac, Philippines",2024-08-07 03:00:00,19.472609,121.431900,asia,PHL,2024-09-05 14:35:25

In [68]:
df3['country_code'].unique()

array(['IND', 'JPN', 'IDN', 'VNM', 'SYR', 'RUS', 'TUR', 'IRN', 'MYS',
       'BTN', 'ARM', 'AFG', 'PHL', 'KGZ', 'CHN', 'MMR'], dtype=object)

In [4]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=SAR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df2 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df2

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,"M 5.7 - 61 km WSW of Challapata, Bolivia",2024-09-05 10:00:00,-19.076091,-67.303800,sar,BOL,2024-09-05 14:35:48
1,DR,"Drought in Bolivia, Brazil, Colombia, Guyana, ...",2024-09-05 00:00:00,-8.500000,-62.500000,sar,BRA,2024-09-05 14:35:48
2,WF,Forest fires in Brazil,2024-09-05 00:00:00,-21.392708,-56.977214,sar,BRA,2024-09-05 14:35:48
3,EQ,"M 4.8 - Off the coast of Aisen, Chile",2024-09-03 01:00:00,-45.555191,-76.704800,sar,CHL,2024-09-05 14:35:48
4,EQ,M 5.3 - southeast of Easter Island,2024-09-02 03:00:00,-36.196691,-100.572000,sar,CHL,2024-09-05 14:35:48
...,...,...,...,...,...,...,...,...
89,EQ,"M 4.6 - 47 km NW of Aroa, Venezuela",2024-08-09 11:00:00,10.793509,-69.204700,sar,VEN,2024-09-05 14:35:48
90,EQ,"M 4.3 - 48 km NNE of Santa Rosa, Peru",2024-08-08 18:00:00,-10.438591,-74.790000,sar,PER,2024-09-05 14:35:48
91,EQ,"M 3.9 - 71 km SSW of La Tirana, Chile",2024-08-08 08:00:00,-20.770591,-70.501800,sar,CHL,2024-09-05 14:35:48
92,WF,Wildfire in Brazil 1020965,2024-08-06 19:00:00,-14.236893,-51.771230,sar,BRA,2024-09-05 14:35:48
93,WF,Wildfire in Brazil 1021051,2024-08-06 19:00:00,-8.615883,-66.571624,sar,BRA,2024-09-05 14:35:48

In [66]:
df2['country_code'].unique()

array(['BOL', 'BRA', 'CHL', 'ARG', 'ECU', 'PER', 'FRA', 'PRY', 'VEN'],
      dtype=object)

In [6]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 2):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=ANT&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df4 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df4

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,M 5.4 - Pacific-Antarctic Ridge,2024-08-29 20:00:00,-62.776791,-158.195300,ant,ATA,2024-09-05 14:35:56
1,EQ,M 5.5 - south of Africa,2024-08-23 04:00:00,-52.862391,21.042700,ant,ATA,2024-09-05 14:35:56
2,EQ,Earthquake in,2024-08-23 04:00:00,-52.937500,19.477102,ant,ATA,2024-08-24 14:36:19
3,SI,Iceberg B22G,2024-08-15 00:00:00,-72.410991,-127.080000,ant,ATA,2024-09-05 14:35:56
4,EQ,M 4.3 - west of Macquarie Island,2024-08-08 06:00:00,-56.140091,146.923600,ant,ATA,2024-09-05 14:35:56

In [7]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 11):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=AFR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df5 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df5

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,DR,"Drought in Burkina Faso, Cote d'Ivoire, Ghana,...",2024-09-05 00:00:00,10.496000,-2.000000,afr,GHA,2024-09-05 14:35:25
1,DR,"Drought in Algeria, Spain, Morocco, Tunisia",2024-09-05 00:00:00,34.500000,-1.000000,afr,DZA,2024-09-05 14:35:25
2,DR,Drought in Madagascar,2024-09-05 00:00:00,-18.500000,46.500000,afr,MDG,2024-09-05 14:35:25
3,DR,"Drought in Angola, Democratic Republic of Cong...",2024-09-05 00:00:00,-12.500000,29.000000,afr,COD,2024-09-05 14:35:25
4,DR,"Drought in Botswana, Namibia, South Africa",2024-09-05 00:00:00,-24.500000,18.000000,afr,NAM,2024-09-05 14:35:25
...,...,...,...,...,...,...,...,...
75,WF,Wildfire in Angola 1021261,2024-08-07 19:00:00,-13.634412,21.050974,afr,AGO,2024-09-05 14:35:25
76,WF,Wildfire in Mozambique 1021247,2024-08-07 19:00:00,-16.944142,37.170331,afr,MOZ,2024-09-05 14:35:25
77,WF,Forest fires in Mozambique,2024-08-07 00:00:00,-13.681085,39.381581,afr,MOZ,2024-08-22 09:15:27
78,WF,Wildfire in Tanzania 1020800,2024-08-06 19:00:00,-3.070008,34.837993,afr,TZA,2024-09-05 14:35:25
79,WF,Wildfire in Angola 1021069,2024-08-06 19:00:00,-11.364514,18.345875,afr,AGO,2024-09-05 14:35:25

In [11]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=EUR&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df6 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df6

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,DR,"Drought in Bulgaria, Belarus, Czech Republic, ...",2024-09-05 00:00:00,50.000500,25.294250,eur,UKR,2024-09-05 14:35:55
1,EQ,"M 5.0 - 109 km WNW of Höfn, Iceland",2024-09-03 16:00:00,64.639409,-17.348200,eur,ISL,2024-09-05 14:35:55
2,EQ,"M 4.1 - 25 km NW of Itháki, Greece",2024-09-02 08:00:00,38.549109,20.482100,eur,GRC,2024-09-05 14:35:55
3,EQ,M 4.4 - Greenland Sea,2024-08-31 14:00:00,79.976209,1.253600,eur,NOR,2024-09-05 14:35:55
4,FL,Flood in Italy,2024-08-29 01:00:00,39.390623,9.167470,eur,ITA,2024-08-30 02:35:08
5,FL,Flood in Austria,2024-08-28 01:00:00,47.253118,11.162612,eur,AUT,2024-08-29 14:36:53
6,EQ,"M 4.4 - 24 km NNE of Cariati, Italy",2024-08-27 12:00:00,39.737709,17.090800,eur,ITA,2024-09-05 14:35:55
7,Misc,"Mass movement in Campania Region, Italy",2024-08-27 12:00:00,40.964583,14.524994,eur,ITA,2024-09-05 14:35:55
8,EQ,"M 4.5 - 18 km E of Istiaía, Greece",2024-08-26 19:00:00,39.017209,23.362100,eur,GRC,2024-09-05 14:35:55
9,EQ,M 4.5 - Svalbard region,2024-08-26 15:00:00,76.304009,6.607700,eur,NOR,2024-09-05 14:35:55
10,EQ,"M 5.4 - 52 km W of Sines, Portugal",2024-08-26 04:00:00,38.055709,-9.465100,eur,PRT,2024-09-05 14:35:55
11,EQ,Earthquake in Portugal,2024-08-26 04:00:00,39.594729,-7.413214,eur,ESP,2024-08-27 14:35:23
12,VO,Eruption Reykjanes,2024-08-22 21:00:00,63.821500,-22.717000,eur,ISL,2024-08-23 14:34:40
13,WF,Wildfire in Serbia 1021761,2024-08-22 19:00:00,43.188142,22.761073,eur,SRB,2024-09-05 14:35:55
14,WF,"Wildfire in Kavala, Greece",2024-08-22 09:00:00,41.001874,24.358886,eur,GRC,2024-09-05 14:35:55
15,EQ,"M 3.5 - 16 km SW of Eresós, Greece",2024-08-21 07:00:00,39.120709,25.793000,eur,GRC,2024-09-05 14:35:55
16,FL,Flood in Slovakia,2024-08-21 01:00:00,48.382754,17.563620,eur,SVK,2024-08-22 14:35:32
17,FL,Flood in Poland,2024-08-20 01:00:00,52.019025,19.195474,eur,POL,2024-08-22 09:24:16
18,TC,Tropical Cyclone ERNESTO-24,2024-08-19 21:00:00,53.800736,-18.400000,eur,IRL,2024-08-22 09:24:14
19,EQ,"M 4.1 - 68 km WSW of Katastárion, Greece",2024-08-17 18:00:00,37.727709,20.005400,eur,GRC,2024-09-05 14:35:55
20,FL,Flood in Belgium,2024-08-16 01:00:00,51.051108,4.364980,eur,BEL,2024-08-22 09:24:11
21,EQ,M 4.4 - Greenland Sea,2024-08-15 18:00:00,74.677609,9.638200,eur,NOR,2024-09-05 14:35:55
22,EQ,"M 4.0 - 9 km N of Babino Polje, Croatia",2024-08-15 03:00:00,42.862709,17.577000,eur,HRV,2024-09-05 14:35:55
23,FL,Flood in Germany,2024-08-15 01:00:00,54.228787,9.487620,eur,DEU,2024-08-22 09:24:10
24,FL,Flood in Spain,2024-08-15 01:00:00,42.097602,-7.148701,eur,ESP,2024-08-22 09:24:10
25,FL,Flood in France,2024-08-15 01:00:00,45.289269,5.633799,eur,FRA,2024-08-22 09:24:10
26,EQ,"M 4.5 - 4 km WNW of Rasinja, Croatia",2024-08-13 06:00:00,46.247109,16.657500,eur,HRV,2024-09-05 14:35:55
27,EQ,"M 4.4 - 19 km S of Karyes, Greece",2024-08-12 13:00:00,40.133809,24.231600,eur,GRC,2024-09-05 14:35:55
28,EQ,M 5.1 - Greenland Sea,2024-08-12 01:00:00,74.742609,8.337100,eur,NOR,2024-09-05 14:35:55
29,WF,"Wildfire in Ukraine, Republic of Moldova 1021286",2024-08-11 19:00:00,46.507748,30.100657,eur,UKR,2024-09-05 14:35:55
30,EQ,"M 4.4 - 6 km N of Ohaba Lungă, Romania",2024-08-10 20:00:00,46.011509,21.983700,eur,ROU,2024-09-05 14:35:55
31,EQ,"M 4.8 - 101 km SW of Kýthira, Greece",2024-08-09 14:00:00,35.448909,22.339500,eur,GRC,2024-09-05 14:35:55
32,FL,Flood in Poland,2024-08-09 01:00:00,50.336743,19.322109,eur,POL,2024-08-22 09:24:03
33,FL,Flood in Estonia,2024-08-08 01:00:00,58.365570,26.686239,eur,EST,2024-08-22 09:24:02
34,WF,"Wildfire in Crete, Greece",2024-08-07 13:00:00,35.154364,24.707011,eur,GRC,2024-09-05 14:35:55
35,EQ,"M 4.2 - 27 km SSE of Moíres, Greece",2024-08-07 08:00:00,34.856509,24.940300,eur,GRC,2024-09-05 14:35:55
36,EQ,"M 4.0 - 3 km W of Grębocice, Poland",2024-08-06 23:00:00,51.650609,16.120200,eur,POL,2024-09-05 14:35:55
37,EQ,"M 4.0 - 3 km W of Grębocice, Poland",2024-08-06 23:00:00,51.650609,16.120200,eur,POL,2024-09-05 14:35:55

In [75]:
df6['country_code'].unique()

array(['UKR', 'ISL', 'GRC', 'NOR', 'ITA', 'AUT', 'PRT', 'ESP', 'SRB',
       'SVK', 'POL', 'IRL', 'BEL', 'HRV', 'DEU', 'FRA', 'ROU', 'EST'],
      dtype=object)

In [8]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=AUS&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df7 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df7

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,Misc,"Burn Off, CUMMING RD",2024-09-05 13:00:00,-32.221516,115.891831,aus,AUS,2024-09-05 14:35:39
1,Misc,"Rescue, NINGALOO-YARDIE CREEK RD",2024-09-05 06:00:00,-22.232085,113.842894,aus,AUS,2024-09-05 14:35:39
2,WF,"Bushfire, HADLEY RD",2024-09-05 05:00:00,-34.054344,115.063464,aus,AUS,2024-09-05 14:35:39
3,Misc,"Vehicle Fire, NORTH WEST COASTAL HWY",2024-09-05 02:00:00,-28.455040,114.634740,aus,AUS,2024-09-05 02:35:35
4,EQ,"M 6.2 - 66 km NNE of Angoram, Papua New Guinea",2024-09-05 01:00:00,-3.437991,144.250800,aus,PNG,2024-09-05 14:35:39
...,...,...,...,...,...,...,...,...
99,EQ,M 4.1 - Kermadec Islands region,2024-08-09 19:00:00,-31.590291,-179.124600,aus,FJI,2024-09-05 14:35:39
100,EQ,"M 4.8 - 121 km SSE of Lorengau, Papua New Guinea",2024-08-09 07:00:00,-3.163109,147.485500,aus,PNG,2024-09-05 14:35:39
101,WF,Forest fires in Australia,2024-08-08 00:00:00,-20.236602,135.017506,aus,AUS,2024-08-22 09:22:39
102,EQ,M 4.2 - south of the Kermadec Islands,2024-08-07 02:00:00,-34.897191,179.189300,aus,NZL,2024-09-05 14:35:39
103,WF,Wildfire in Papua New Guinea 1021077,2024-08-06 19:00:00,-4.213882,144.009935,aus,PNG,2024-09-05 14:35:39

In [9]:
import http.client
import json
import pandas as pd

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
}

all_data = []

for i in range(1, 6):
    conn = http.client.HTTPSConnection("api.ambeedata.com")
    conn.request("GET", f"/disasters/latest/by-continent?continent=OCEAN&limit=50&page={i}", headers=headers)
    
    res = conn.getresponse()
    data = res.read()
    data = data.decode("utf-8")
    json_data = json.loads(data)

    if 'result' in json_data:
        all_data.extend(json_data['result'])
    
    conn.close()

# Create DataFrame from the collected data
df8 = pd.DataFrame(all_data)[['event_type', 'event_name', 'date', 'lat', 'lng', 'continent', 'country_code', 'created_time']]
df8

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,M 4.8 - northern Mid-Atlantic Ridge,2024-09-01 15:00:00,26.431409,-44.561300,ocean,PRT,2024-09-05 14:35:39
1,EQ,M 4.7 - South Sandwich Islands region,2024-08-22 01:00:00,-55.960091,-30.779200,ocean,SGS,2024-09-05 14:35:39
2,EQ,M 5.0 - southern Mid-Atlantic Ridge,2024-08-21 06:00:00,-16.572091,-14.570600,ocean,SHN,2024-09-05 14:35:39
3,TC,Tropical Cyclone ERNESTO-24,2024-08-20 15:00:00,51.533716,-30.010580,ocean,PRT,2024-08-22 09:30:37
4,EQ,M 4.7 - South Georgia Island region,2024-08-18 08:00:00,-55.105491,-31.205000,ocean,SGS,2024-09-05 14:35:39
5,FL,Flood in Maldives,2024-08-15 01:00:00,3.281714,73.247658,ocean,MDV,2024-08-22 09:30:32
6,EQ,M 4.4 - Mauritius - Reunion region,2024-08-09 10:00:00,-19.952591,66.498000,ocean,MUS,2024-09-05 14:35:39
7,EQ,M 4.5 - South Sandwich Islands region,2024-08-07 11:00:00,-59.793391,-26.854900,ocean,SGS,2024-09-05 14:35:39

In [20]:
disaster = pd.concat([data,df,df1,df2,df3,df4,df5,df6,df7,df8], axis=0, ignore_index=True)
disaster.to_csv("disaster_data.csv")

In [21]:
disaster

,event_type,event_name,date,lat,lng,continent,country_code,created_time
0,EQ,NORTHERN ALASKA,2024-09-05 12:00:00,65.881200,-152.217900,nar,USA,2024-09-05 14:35:56
1,DR,"Drought in Guatemala, Honduras, Mexico, Nicaragua",2024-09-05 00:00:00,18.500000,-99.000000,nar,MEX,2024-09-05 14:35:56
2,DR,Drought in Canada,2024-09-05 00:00:00,53.500000,-116.000000,nar,CAN,2024-09-05 14:35:56
3,EQ,CALIFORNIA-NEVADA BORDER REGION,2024-09-04 11:00:00,36.523300,-115.540000,nar,USA,2024-09-05 14:35:56
4,EQ,CENTRAL CALIFORNIA,2024-09-04 11:00:00,37.282500,-119.999000,nar,USA,2024-09-05 14:35:56
...,...,...,...,...,...,...,...,...
1474,TC,Tropical Cyclone ERNESTO-24,2024-08-20 15:00:00,51.533716,-30.010580,ocean,PRT,2024-08-22 09:30:37
1475,EQ,M 4.7 - South Georgia Island region,2024-08-18 08:00:00,-55.105491,-31.205000,ocean,SGS,2024-09-05 14:35:39
1476,FL,Flood in Maldives,2024-08-15 01:00:00,3.281714,73.247658,ocean,MDV,2024-08-22 09:30:32
1477,EQ,M 4.4 - Mauritius - Reunion region,2024-08-09 10:00:00,-19.952591,66.498000,ocean,MUS,2024-09-05 14:35:39
1478,EQ,M 4.5 - South Sandwich Islands region,2024-08-07 11:00:00,-59.793391,-26.854900,ocean,SGS,2024-09-05 14:35:39

In [1]:
import http.client

conn = http.client.HTTPSConnection("api.ambeedata.com")

headers = {
    'x-api-key': "09a5c00568c2d46e92365e5640dfac275d0ce75cfc6b4115f12890c3e3347477",
    'Content-type': "application/json"
    }

conn.request("GET", "/disasters/history/by-continent?continent=NAR&from=2023-05-01%2020%3A16%3A44&to=2024-06-01%2000%3A00%3A00&limit=10&page=1", headers=headers)

res = conn.getresponse()
data = res.read()

print(data.decode("utf-8"))

{"message":"No active subscription found"}